name: Compile Android Native Mod Project
on:
  workflow_dispatch:

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '25.2.9519653' # Standard stable NDK version

      - name: Unzip Source Code
        run: |
          # Agar aapne poori zip file upload ki hai to use extract karein
          if [ -f kernelsorce.zip ]; then
            unzip kernelsorce.zip
          fi

      - name: Compile using ndk-build
        run: |
          # Jahaan Android.mk file hai us directory me jaakar compile karein
          TARGET_DIR=$(find . -name "jni" -type d | head -n 1)
          if [ -d "$TARGET_DIR" ]; then
            cd "$TARGET_DIR"/..
            $ANDROID_NDK_LATEST_HOME/ndk-build
          else
            echo "Error: jni folder nahi mila!" && exit 1
          fi

      - name: Upload Output Compiled Libraries (.so files)
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-Mod-Libraries
          path: '/libs//*'
